# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_create_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Restaurant')),
            ],
            options={
                'db_table': 'places_waiters',
            },
        ),
    ]
