# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField()),
            ],
            options={
                'ordering': ('horn_length',),
                'db_table': 'animals_oxen',
                'verbose_name_plural': 'oxen',
            },
        ),
    ]
