# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_create_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.ManyToManyField(to='pizzas.Topping')),
            ],
            options={
                'db_table': 'pizzas_pizzas',
            },
        ),
    ]
