# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], default=b'S', max_length=1),
        ),
    ]
