# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 15:44
from __future__ import unicode_literals

from django.utils import timezone

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_create_group_and_membership_20180619_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
