# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('people.person',),
        ),
    ]
